spring:
  application:
    name: Zuul-Server
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server.mukul-k.svc:8080/eureka
  instance:
    preferIpAddress: true   
    
zuul:
  #Service will be mapped under the /api URI
 prefix: /api
 routes:
    date-client:
      path: /date-client/**
      serviceId: Eureka-Date-Client
    hello-client:
      path: /hello-client/**
      serviceId: Eureka-Hello-Client
    zuul-server:
      path: /zuul-server/**
      serviceId: Zuul-Server
     
